name: "Setup"
description: Setup action

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile