name: Deploy

# Deploys are manually triggered
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Deploy as prerelease'
        required: true
        type: boolean

jobs:
  deploy:
    name: 'Deploy'
    timeout-minutes: 15
    runs-on: ubuntu-latest # TODO: this should probably run on multiple OSes

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Deploy
        run: pnpm deploy

      # - name: Check API declarations and docs work as intended
      #   run: pnpm api:check
