name: Checks

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches: [main]

jobs:
  build:
    name: 'Enforce label'
    timeout-minutes: 15
    runs-on: ubuntu-latest # TODO: this should probably run on multiple OSes

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Require label
        run: pnpm check-pr-label
